var models = {
		
		"hasCampaignTypes": {
			"idAdvertiser":0,
			"idCampaignType":0,
			"idCampaignSubType":0,
			"businessName":"",
			"cobrandName":"",
			"productName":"",
			"businessId":0,
			"cobrandId":0,
			"offerId":0

		},
		"offerMetadatas":{
			"id":0,
			"idOffer":0,
			"metadataName":"",
			"metadataDescription":"",
			"metadataType":"",
			"metadataOptions":"",
			"metadataValidations":"",
			"metadataHelp":"",
			"metadataSortOrder":0
		},
		"offerOptions":{
			"id":0,
			"idOffer":0,
			"ooTableName":"",
			"ooTableValue":""
		},
		"offerBundle":{
			"idOfferBundle":0,
			"idOffer":0,
			"allocationPercentage":0.0
		},
		"productFamilyOffer":{
			"offerId":0,
			"isAddon":false,
			"productAbbreviation":"",
			"productFamilyName":"",
			"displayOrder":0,
			"productFamilyId":0
		},
		"hasMarginPercents":{
			"id":0,
			"idOffer":0,
			"idWebPublisher":0,
			"idCampaignSubType":0,
			"idCampaignType":0,
			"idAdvertiserMaster":0,
			"idBusiness":0,
			"idCobrand":0,
			"idRenewFactor":0,
			"startDate":new Date().toISOString().slice(0,10),
			"endDate": new Date().toISOString().slice(0,10),
			"minBudget":0.00,
			"maxBudget":9999999.99,
			"markUpPercent":0.0,
			"markDownPercent":0.0,
			"idPerformancePricingValues":0,
			"lastModified": new Date().toISOString().slice(0,10)
		},
		"hasDefaultOffers":{
			"idWebPublisher":0,
			"idBusinessSubCategory":0,
			"idBusinessCategory":0,
			"idGeoTarget":0,
			"idTargetType":0,
			"minBudget":0.00,
			"maxBudget":9999999.99,
			"lastModified": new Date().toISOString().slice(0,10),
			"idOffer":0,
			"idCoBrand":0,
			"idCampaignSubType":0,
			"idCampaignType":0
			
		},
		"offerProductURI":{
			"idOffer":0,
			"productURI":""
		},
		"offerHasCreativeTypes":{
			"id":0,
			"idOffer":0,
			"idCreativeType":0,
			"idCreativeFields":0,
			"idMediaAttributes":0,
			"required":true,
			"mediaAttributeValue":""
			
		},
		"offerHasEnhancedCreativeGroups":{
			"id":0,
			"idOffer":0,
			"idEnhancedCreativeGroup":0,
			"idCreativeFields":0,
			"idMediaAttributes":0,
			"required":true,
			"mediaAttributeValue":""
		},
		"campaignFormTemplates":{
			"id":0,
			"idCampaignType":0,
			"idCampaignSubType":0,
			"idOffer":0,
			"idCampaignCreationElement":0,
			"elementDisplayName":"",
			"elementOrder":0,
			"idCampaignCreationDisplayGroup":0,
			"displayGroupName":"",
			"displayGroupOrder":0,
			"helpText":"",
			"allowsEditing":true,
			"displayElement":true,
			"pageNumber":1,
			"pageLabel":"",
			"allowsRenew":false,
			"allowsEditingIoMode":true
		},
		"campaignValidationRules":{
			"id":0,
			"idCampaignType":0,
			"idCampaignSubType":0,
			"idOffer":0,
			"campaignParameter":"",
			"isRequired":false,
			"allowsEditing":true,
			"minConstraint":"",
			"maxConstraint":"",
			"defaultValue":"",
			"constraintType":"",
			"description":""
		},
		"platformOfferProducts":{
			"platform":"",
			"offerid":"",
			"product":""
		}
		
}